controllers/CatalogController.php
<?php
/**
 * Created by PhpStorm.
 * User: krainov
 * Date: 04.04.2018
 * Time: 23:47
 */

namespace app\controllers;

use app\models\Item;
use yii\data\Pagination;
use yii\web\HttpException;

class CatalogController extends AppController
{

    public function actionIndex($name = '')
    {
        $this->layout = 'index';
        //$items = Item::find()->orderBy('id DESC')->all();

        // Пагинация
        $query = Item::find()->orderBy('id DESC');
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 3, 'pageSizeParam' => false, 'forcePageParam' => false]);
        $items = $query->offset($pages->offset)->limit($pages->limit)->all();

        return $this->render('index', compact('items', 'pages'));
    }

    public function actionView(){
        $id = \Yii::$app->request->get('id');
        $item = Item::findOne($id);
        if(empty($item)) throw new HttpException(404, 'Такой страницы не существует');

        return $this->render('view', compact('item'));
    }
}

views/catalog/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Каталог окон';

?>
<div class="container mb60 page-styling row-wrap-container row-wrap-nottl">
    <p class="maincont-subttl">Популярные товары</p>
    <h2 id="catalog-main" class="mb35 heading-multishop">Каталог окон</h2>
    <div class="row prod-items prod-items-3">
        <? foreach ($items as $item) {
        ?>
        <article class="cf-sm-6 cf-md-4 cf-lg-4 col-xs-6 col-sm-6 col-md-4 col-lg-4 sectgl-item">
            <div class="sectgl prod-i">
                <div class="prod-i-top">
                    <a class="prod-i-img" href="<?=\yii\helpers\Url::to(['catalog/view', 'id'=> $item->id])?>">
                        <img src="http://placehold.it/290x258" alt="">
                    </a>
                    <div class="prod-i-actions">
                        <div class="prod-i-actions-in">
                            <p class="prod-quickview">
                                <a href="#" class="hover-label quick-view"><i class="icon ion-plus"></i><span>Быстрый просмотр</span></a>
                            </p>
                            <p class="prod-i-cart">
                                <a href="#" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Добавить в корзину</span></a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="prod-i-bot">
                    <div class="prod-i-info">
                        <p class="prod-i-price">$120.00</p>
                        <p class="prod-i-categ"><a href="<?=\yii\helpers\Url::to(['catalog/view', 'id'=> $item->id])?>"><?=$item->type?></a></p>
                    </div>
                    <h3 class="prod-i-ttl"><a href="<?=\yii\helpers\Url::to(['catalog/view', 'id'=> $item->id])?>"><?=$item->title?></a></h3>
                </div>
            </div>
        </article>
        <?}?>
    </div>
    <?= \yii\widgets\LinkPager::widget(['pagination' => $pages])?>
    <p class="special-more">
        <a class="special-more-btn" href="#">Показать ещё</a>
    </p>

</div>

views/catalog/view.php
<?php

/* @var $this yii\web\View */

$this->title = $item->title;

$this->params['breadcrumbs'][] = ['label' => 'Каталог', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<article>
    <div class="prod">
        <div class="prod-slider-wrap prod-slider-shown">
            <div class="flexslider prod-slider" id="prod-slider">
                <ul class="slides">
                    <li>
                        <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/810x722">
                            <img src="http://placehold.it/550x490" alt="">
                        </a>
                    </li>
                    <li>
                        <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/800x800">
                            <img src="http://placehold.it/550x550" alt="">
                        </a>
                    </li>
                </ul>
                <div class="prod-slider-count"><p><span class="count-cur">1</span> / <span class="count-all">2</span></p><p class="hover-label prod-slider-zoom"><i class="icon ion-search"></i><span>Zoom In</span></p></div>
            </div>
            <div class="flexslider prod-thumbs" id="prod-thumbs">
                <ul class="slides">
                    <li>
                        <img src="http://placehold.it/550x490" alt="">
                    </li>
                    <li>
                        <img src="http://placehold.it/550x550" alt="">
                    </li>
                </ul>
            </div>
        </div>

        <div class="prod-cont">
            <p class="prod-categs"><a href="#"><?=$item->type?></a></p>
            <h1><?=$item->title?></h1>
            <div class="variations_form cart">
                <p class="prod-price">$140.00</p>
                <p class="prod-excerpt"><?=$item->content?> <a id="prod-showdesc" class="prod-excerpt-more" href="#">read more</a></p>
                <div class="prod-add">
                    <button type="submit" class="button"><i class="icon ion-android-cart"></i> В корзину</button>
                    <p class="qnt-wrap prod-li-qnt">
                        <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                        <input type="text" value="1">
                        <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                    </p>
                </div>
            </div>
            <div class="prod-props">
                <dl class="product_meta">
                    <dt>Артикул:</dt>
                    <dd><?=$item->vendor?></dd>
                    <dt>Тип:</dt>
                    <dd><?=$item->type?></dd>
                    <dt>Открывание:</dt>
                    <dd><?=$item->opening?></dd>
                    <dt>Геометрия:</dt>
                    <dd><?=$item->geometry?></dd>
                    <dt>Стеклопакет:</dt>
                    <dd><?=$item->type_windows?></dd>
                    <dt>Цвет снаружи:</dt>
                    <dd><?=$item->color_outside?></dd>
                    <dt>Цвет внутри:</dt>
                    <dd><?=$item->color_inside?></dd>
                    <dt>Высота окна:</dt>
                    <dd><?=$item->height?></dd>
                    <dt>Ширина окна:</dt>
                    <dd><?=$item->width?></dd>
                    <dt>Параметры:</dt>
                    <dd><?=$item->options?></dd>

                </dl>
            </div>
        </div>
        <p class="prod-badge">
            <span class="badge-1">TOP SELLER</span>
        </p>
    </div>

</article>